version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo 'install phase'
      - pip install -r ./automatic_classification_illegal_av__get_crawl_url_list/requirements.txt -t ./automatic_classification_illegal_av__get_crawl_url_list
      - pip install -r ./automatic_classification_illegal_av__html_download/requirements.txt -t ./automatic_classification_illegal_av__html_download
  build:
    commands:
      - echo 'build phase'
      - zip automatic_classification_illegal_av__get_crawl_url_list.zip ./automatic_classification_illegal_av__get_crawl_url_list/*
      - zip automatic_classification_illegal_av__html_download.zip ./automatic_classification_illegal_av__html_download/*
  post_build:
    commands:
      - aws s3 cp automatic_classification_illegal_av__get_crawl_url_list.zip s3://automatic.classification.illegal.av/code_build/
      - aws s3 cp automatic_classification_illegal_av__html_download.zip s3://automatic.classification.illegal.av/code_build/