version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo 'install phase'
      - pip install -r ./automatic_classification_illegal_av__get_crawl_url_list/requirements.txt -t ./automatic_classification_illegal_av__get_crawl_url_list
  build:
    commands:
      - echo 'build phase'
      - zip automatic_classification_illegal_av__get_crawl_url_list.zip ./automatic_classification_illegal_av__get_crawl_url_list/*
artifacts:
  name: root-artifact
  base-directory: ./
  secondary-artifacts:
    artifactIdentifier:
      artifact__automatic_classification_illegal_av__get_crawl_url_list:
        base-directory: './'
        discard-paths: no
        files:
          - './automatic_classification_illegal_av__get_crawl_url_list.zip'